---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: juicefs-dev-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: "https://juicefs.loca.lt/mutate"
  failurePolicy: Fail
  name: juicefs.breuer.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
