---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.controller.annotations }}
  annotations:
{{ toYaml .Values.controller.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.controller.image }}:{{ .Values.controller.tag }}
        imagePullPolicy: Always
{{- if or .Values.controller.podAnnotation .Values.controller.storageClasses }}
        args:
{{- if .Values.controller.podAnnotation }}
        - "-pod-annotation"
{{- end }}
{{- if .Values.controller.storageClasses }}
        - "-storage-classes={{ .Values.controller.storageClasses }}"
{{- end }}
{{- end }}
        volumeMounts:
        - name: tls
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tls
          secret:
            secretName: {{ .Chart.Name }}-tls
            optional: false

