---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Chart.Name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ .Chart.Name }}
      port: 9443
      path: "/mutate-pod"
  failurePolicy: Fail
  name: juicefs.breuer.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None

